/**
 * Creates component from tagged template literal.
 * @param strings Generated by tagged template literal.
 * @param args Generated by tagged template literal.
 * @returns Generated markup.
 */
export function guac(
  strings: TemplateStringsArray,
  ...args: (string | string[])[]
): string {
  const res: string = strings.reduce((acc, str, i) => {
    const arg = args[i - 1];

    if (Array.isArray(arg)) {
      return acc + arg.join("") + str;
    }

    return acc + args[i - 1] + str;
  });

  return res.trim().replace(/\s{2,}/g, " ").trim();
}
