/**
 * Creates a component from a tagged template literal.
 * @param {TemplateStringsArray} strings The template strings generated by the tagged template literal.
 * @param {...(string|string[])} args The values generated by the tagged template literal.
 * @returns {string} The generated markup.
 */
export function guac(
  strings: TemplateStringsArray,
  ...args: (string | string[])[]
): string {
  const res: string = strings.reduce((acc, str, i) => {
    const arg = args[i - 1];

    if (Array.isArray(arg)) {
      return acc + arg.join("") + str;
    }

    return acc + args[i - 1] + str;
  });

  return res.trim().replace(/\s{2,}/g, " ").replaceAll("> <", "><").trim();
}
